In [1]:
import numpy as np

In [6]:
# Create arrays

np.zeros(10)
np.ones(10)
np.full(10, 1)
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [7]:
# Multidimensional arrays

np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Randomly generated arrays

np.random.seed(100)
np.random.randn(5, 3)

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884],
       [ 0.22117967, -1.07004333, -0.18949583],
       [ 0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081]])

In [19]:
# Element-wise operations

a = np.arange(10)
a + 1
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])